baseURL = 'http://eddie.id/'
languageCode = 'en-us'
title = 'My Personal Website'

[build]
  writeStats = true

[params]
    title = "Eddie Website"
    author = "Eddie Mashayev"
    description = "Website title"
#    copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        showAttribute = true
        singlePage = false

    # Profile section
    [params.profile]
        name = "Eddie Mashayev"
        tagline = "Software Engineer"
        location = "New York City, NY"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/edmashayevdevopsengineer/"
            title = "LinkedIn"
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "https://stackoverflow.com/users/2056768/eddiem"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/mashayev"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/EMashayev"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = """Experienced DevOps professional with 10+ years in software lifecycle management, skilled in Python, Bash, Groovy, CI/CD pipelines, AWS, Docker/Kubernetes, Terraform and Ansible.
        Strong in cloud, automation, and team collaboration. Self-motivated, able to work independently and as part of a team."""

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Senior DevOps Engineer"
            dates = "2018 - *Present*"
            url = "https://www.armis.com/"
            company = "Armis Security"
            # details = "Senior DevOps Engineer"
        [[params.experience.list]]
            position = "DevOps Manager"
            dates = "2016 - 2018"
            url = "https://www.integrate.io/"
            company = "Integrate (Xplenty - acquired)"
        [[params.experience.list]]
            position = "IT Automation Engineer (DevOps)"
            dates = "2015 - 2016"
            url = "https://www.imperva.com/"
            company = "Imperva (acquired)"
        [[params.experience.list]]
            position = "System UNIX/Linux admin"
            dates = "2010 - 2015"
            url = "https://www.amdocs.com/"
            company = "Amdocs"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Software Engineer"
            college = "Afeka collage of engineering"
            dates = "2008 - 2013"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python, bash, groovy"
            skillrating = 90
        [[params.skill.list]]
            skill = "AWS"
            skillrating = 90
        [[params.skill.list]]
            skill = "Terraform, Ansible"
            skillrating = 89
        [[params.skill.list]]
            skill = "CI / CD - Jenkins"
            skillrating = 88
        [[params.skill.list]]
            skill = "Docker, Kubernetes"
            skillrating = 88
        [[params.skill.list]]
            skill = "Prometheus, Grafana"
            skillrating = 88

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Gym"
        [[params.hobby.list]]
            hobby = "Coffee"
        [[params.hobby.list]]
            hobby = "Gaming"
